### ISSUE TITLE
not working review with czech locales

### ISSUE THREAD

**Issue by McQuak** [diefenbach/django-lfs#168] opened 2015-01-18 18:34 UTC
Customer making review of product, is getting message:
Select a valid choice. "1,0" is not one of the available choices.

Problem is because code doesn't expect number in local form 1,0 but only 1.0

**Comment by pigletto** [comment] 2015-01-18 19:20
I'm not able to reproduce that with 'cs_CS.UTF-8' locale.

Values for reviews are defined here: https://github.com/diefenbach/django-reviews/blob/master/reviews/settings.py and I can't find a place where it could be 'localized' to '1,0'. On review add form I have '1.0', eg.:

```
    <div class="star-rating-wrapper">
        <ul class="star-rating">
                    <li>
                        <a href="#" class="rate" title="1" data="1.0" style="z-index:10; width:25px">
                        </a>
                    </li>
                
                    <li>
                        <a href="#" class="rate current-rating" title="2" data="2.0" style="z-index:9; width:50px">
                        </a>
                    </li>
                
                    <li>
                        <a href="#" class="rate" title="3" data="3.0" style="z-index:8; width:75px">
                        </a>
                    </li>
                
                    <li>
                        <a href="#" class="rate" title="4" data="4.0" style="z-index:7; width:100px">
                        </a>
                    </li>
                    <li>
                        <a href="#" class="rate" title="5" data="5.0" style="z-index:6; width:125px">
                        </a>
                    </li>
        </ul>
    </div>
```

Do you have any modifications to reviews form, theme etc?

**Comment by McQuak** [comment] 2015-01-27 20:50
My review form is not modified

In settings.py is 
SCORE_CHOICES = (
(1.0, _(u"*")),
(2.0, _(u"**")),

But on the web page is 
        <div class="star-rating-wrapper">
            
            <ul class="star-rating">
                
                    <li>
                        <a href="#"
                           class="rate "
                           title="1"
                           data="1,0"
                           style="z-index:10; width:25px">
                        </a>
                    </li>
                
                    <li>
                        <a href="#"
                           class="rate "
                           title="2"
                           data="2,0"
                           style="z-index:9; width:50px">
                        </a>
                    </li>
                
                    <li>
                        <a href="#"
                           class="rate "
                           title="3"
                           data="3,0"
                           style="z-index:8; width:75px">
                        </a>
                    </li>
                
                    <li>
                        <a href="#"
                           class="rate "
                           title="4"
                           data="4,0"
                           style="z-index:7; width:100px">
                        </a>
                    </li>
                
                    <li>
                        <a href="#"
                           class="rate "
                           title="5"
                           data="5,0"
                           style="z-index:6; width:125px">
                        </a>
                    </li>

**Comment by McQuak** [comment] 2015-01-27 20:51
Sorry wrong button

**Comment by pigletto** [comment] 2015-01-27 21:12
I still can't reproduce that. What version of LFS and reviews application do you have?

Can you try the following (on dev server: bin/django runserver):
find reviews application and modify reviews/reviews/views.py -> add_form method, line 74 (https://github.com/diefenbach/django-reviews/blob/master/reviews/views.py#L74):

by adding:

``` 
print "Scores: ", scores
```

then visit the "Add review" page and check out the console output. It shoud show "Scores: ....." .
If it shows numerical values without ',' then check if you have any modifications to reviews/review_form.html

Your SCORE_CHOICES are not default ones so is there a chance that something else is not default too?

**Comment by McQuak** [comment] 2015-01-28 00:23
I use version from github by -e git+git://github.com/diefenbach/django-lfs.git#egg=django-lfs
or django-lfs==0.9.0a1 - problem is same 

On console is 
Scores:  [{'width': 25, 'z_index': 10, 'value': 1.0, 'title': 1.0}, {'width': 50, 'z_index': 9, 'value': 2.0, 'title': 2.0}, {'width': 75, 'z_index': 8, 'value': 3.0, 'title': 3.0}, {'width': 100, 'z_index': 7, 'value': 4.0, 'title': 4.0}, {'width': 125, 'z_index': 6, 'value': 5.0, 'title': 5.0}]

My review_form.html is same as is in lfs-theme:
```pyhton
                {% for score in scores %}
                    <li>
                        <a href="#"
                           class="rate {% if score.current %}current-rating{% endif %}"
                           title="{{ score.title|floatformat }}"
                           data="{{ score.value }}"
                           style="z-index:{{ score.z_index }}; width:{{ score.width }}px">
                        </a>
                    </li>
                {% endfor %}
```

My SCORE_CHOICES is default - just github made some changes 
```pyhton
# django imports
from django.utils.translation import ugettext_lazy as _

SCORE_CHOICES = (
    (1.0, _(u"*")),
    (2.0, _(u"**")),
    (3.0, _(u"***")),
    (4.0, _(u"****")),
    (5.0, _(u"*****")),
)
```

**Comment by McQuak** [comment] 2015-01-28 01:22
I found easy solution:
data="{{ score.value|floatformat:0 }}"

Is it some reason to use float for value?

**Comment by pigletto** [comment] 2015-01-28 19:38
Resolved in: https://github.com/diefenbach/lfs-theme/commit/c256aadb9ea4b8e3532a99b2979016a3ea22a23c

Thanks for reporting!

**Closed by pigletto** 2015-01-28 19:38 UTC
